### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by meechew** [xuchunyang/code-stats-emacs#4]
I do not know what to do with the code in the readme file. Should I run it once? put it in the .emacs file? please advise.

**Comment by xuchunyang** [comment]
You need to understand the sample config in the README, and change it accordingly, and ask Emacs to evaluate it.

---

>     (setq code-stats-token "your-token")

Setup your personal token. Be aware don't share the token publicly.

>     (add-hook 'prog-mode-hook #'code-stats-mode)

The minor mode `code-stats-mode` tracks the stats. This line enables the mode in all programming buffers.

>      (run-with-idle-timer 30 t #'code-stats-sync)

The function `code-stats-sync` sends the stats to codestats.net. This line tells Emacs to sync when each time Emacs idles for 30s.

>     (add-hook 'kill-emacs-hook (lambda () (code-stats-sync :wait)))

When Emacs exits, this line tells Emacs to sync and waits till it finishes.
